### ISSUE TITLE
Unable to target the autoscaler api endpoint

### ISSUE THREAD

**Issue by lalitrawat16** [cloudfoundry-incubator/app-autoscaler-cli-plugin#16]
Unable to target the autoscaler api endpoint using the command cf autoscaling-api as part of the autoscaler-cli-plugin.

**Comment by rohitsharma04** [comment]
@lalitrawat16 can you provide some more information like what url you're trying to target and where is your app-autoscaler deployed, version etc.

**Comment by radovanthefoley** [comment]
@rohitsharma04 I am having the same difficulty. Cannot find documentation describing how to find out how autoscaler api endpoint should look like. Can you please try to explain without further details replacing real urls with placeholders?
Let's say I know my CF API endpoint ("https://api.something.io:). Is that somehow used in order to get to autoscaler api endpoint? I have tried as "https://autoscaler.api.something.io" but with no luck.

Thanks

**Comment by rohitsharma04** [comment]
@radovanthefoley the url you're using is incorrect.
 As for your example if the cf api endpoint is
`https://api.something.io` then autoscaler api endpoint will be `https://autoscaler.something.io`

**Comment by radovanthefoley** [comment]
@rohitsharma04 thanks. Hope this helps to anybody passing by the same problem.

**Comment by cdlliuy** [comment]
@radovanthefoley  @lalitrawat16  sorry for the issue. we have some documentation effort on going now,  but not ready yet ..

**Comment by boyang9527** [comment]
closing given guide is added in document
